server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3380/demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#-------mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

  type-aliases-package: com.miaohy.demo.entity

logging:
  level:
    com.miaohy.demo: debug